#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
exports a .txt file of the distance between residue i and all other residues in a random coil
with length N

currently set for i = 48 (residue 927 in ctFCP1) and N = 83


Created on Tue Oct 16 10:20:47 2018

@author: Victor Prieto
"""

from math import pi

i = 48
N = 83

def distance(i, N):
    b = 3.8
    term_1_denominator =2*pi*(N-1)*(b**2)
    if term_1_denominator != 0:
        term_1 = (3/term_1_denominator)**0.5
        term_2 = (-3*(i**2))/(2*N*(b**2))
        return(term_1**term_2)
    else:
        return 0

dis_927 = []

for x in range(1, N):
    dis_927.append(distance(i, x))
    
print('distance? \n', dis_927)
print(len(dis_927))